language: cpp

script: make

sudo: required

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6-dev
      - clang-3.6
      - libpcap-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi
