language: cpp

script: make

os:
  - linux
  - osx
compiler:
  - clang
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi ; di

  # clang 3.4
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi ; fi

addons:
  apt:
    packages:
      - libpcap-dev
