language: cpp

script: make

os:
  - linux
  - osx
compiler:
  - clang
  - gcc

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

addons:
  apt:
    packages:
      - libpcap-dev
