language: cpp

script: make

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libpcap-dev
        env: COMPILER=g++-4.8
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libpcap-dev
        env: COMPILER=clang++-3.4
    - os: osx
      compiler: clang

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

addons:
  apt:
    packages:
      - libpcap-dev
