language: cpp

script: make

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - g++-4.8
            - libpcap-dev
        env: CXX=g++-4.8
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages:
            - clang-3.4
            - libpcap-dev
        env: CXX=clang++-3.4
    - os: osx
      compiler: clang
